"""add refresh token id

Revision ID: b51b971c8729
Revises: 331c2e4e7e52
Create Date: 2026-07-24 19:06:50.206302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51b971c8729'
down_revision: Union[str, Sequence[str], None] = '331c2e4e7e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token_id', sa.UUID(), nullable=False))
    op.add_column('user_sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_sessions_refresh_token_id'), 'user_sessions', ['refresh_token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'last_used_at')
    op.drop_column('user_sessions', 'refresh_token_id')
    # ### end Alembic commands ###
